export enum ClaimsConstants {
    ON_GET_COMMUNITY_CLAIMS_REQUESTED = 'ON_GET_COMMUNITY_CLAIMS_REQUESTED',
    COMMUNITY_CLAIMS_SUCCEEDED = 'COMMUNITY_CLAIMS_SUCCEEDED',
    COMMUNITY_CLAIMS_FAILED = 'COMMUNITY_CLAIMS_FAILED',
    UPDATE_CLAIM_REQUESTED = 'UPDATE_CLAIM_REQUESTED',
    UPDATE_CLAIM_SUCCEEDED = 'UPDATE_CLAIM_SUCCEEDED',
    UPDATE_CLAIM_FAILED = 'UPDATE_CLAIM_FAILED',
}
