export enum ClaimsConstants {
    ON_GET_COMMUNITY_CLAIMS_REQUESTED = 'ON_GET_COMMUNITY_CLAIMS_REQUESTED',
    COMMUNITY_CLAIMS_SUCCEEDED = 'COMMUNITY_CLAIMS_SUCCEEDED',
    COMMUNITY_CLAIMS_FAILED = 'COMMUNITY_CLAIMS_FAILED',
}
