export const COMMUNITY_ON_SIGN_UP_REQUESTED = 'COMMUNITY_ON_SIGN_UP_REQUESTED';
export const COMMUNITY_ON_SIGN_UP_SUCCEEDED = 'COMMUNITY_ON_SIGN_UP_SUCCEEDED';
export const COMMUNITY_ON_SIGN_UP_FAILED = 'COMMUNITY_ON_SIGN_UP_FAILED';

export const COMMUNITY_ON_LOGIN_REQUESTED = 'COMMUNITY_ON_LOGIN_REQUESTED';
export const COMMUNITY_ON_LOGIN_SUCCEEDED = 'COMMUNITY_ON_LOGIN_SUCCEEDED';
export const COMMUNITY_ON_LOGIN_FAILED = 'COMMUNITY_ON_LOGIN_FAILED';

export const ON_GET_ALL_COMMUNITIES_REQUESTED = 'ON_GET_ALL_COMMUNITIES_REQUESTED';
export const ON_GET_ALL_COMMUNITIES_SUCCEEDED = 'ON_GET_ALL_COMMUNITIES_SUCCEEDED';
export const ON_GET_ALL_COMMUNITIES_FAILED = 'ON_GET_ALL_COMMUNITIES_FAILED';

export const ON_GET_COMMUNITY_PROFILE_REQUESTED = 'ON_GET_COMMUNITY_PROFILE_REQUESTED';
export const ON_GET_COMMUNITY_PROFILE_SUCCEEDED = 'ON_GET_COMMUNITY_PROFILE_SUCCEEDED';
export const ON_GET_COMMUNITY_PROFILE_FAILED = 'ON_GET_COMMUNITY_PROFILE_FAILED';