export const COMMUNITY_ON_SIGN_UP_REQUESTED = 'COMMUNITY_ON_SIGN_UP_REQUESTED';
export const COMMUNITY_ON_SIGN_UP_SUCCEEDED = 'COMMUNITY_ON_SIGN_UP_SUCCEEDED';
export const COMMUNITY_ON_SIGN_UP_FAILED = 'COMMUNITY_ON_SIGN_UP_FAILED';

export const COMMUNITY_ON_LOGIN_REQUESTED = 'COMMUNITY_ON_LOGIN_REQUESTED';
export const COMMUNITY_ON_LOGIN_SUCCEEDED = 'COMMUNITY_ON_LOGIN_SUCCEEDED';
export const COMMUNITY_ON_LOGIN_FAILED = 'COMMUNITY_ON_LOGIN_FAILED';