export const ON_GET_PLACES_REQUESTED = 'ON_GET_PLACES_REQUESTED';
export const ON_GET_PLACES_SUCCEEDED = 'ON_GET_PLACES_SUCCEEDED';
export const ON_GET_PLACES_FAILED = 'ON_GET_PLACES_FAILED';

export const ON_CREATE_PLACE_REQUESTED = 'ON_CREATE_PLACE_REQUESTED';
export const ON_CREATE_PLACE_SUCCEEDED = 'ON_CREATE_PLACE_SUCCEEDED';
export const ON_CREATE_PLACE_FAILED = 'ON_CREATE_PLACE_FAILED';

export const ON_EDIT_A_PLACE_REQUESTED = 'ON_EDIT_A_PLACE_REQUESTED';
export const ON_EDIT_A_PLACE_SUCCEEDED = 'ON_EDIT_A_PLACE_SUCCEEDED';
export const ON_EDIT_A_PLACE_FAILED = 'ON_EDIT_A_PLACE_FAILED';

export const ON_GET_PLACE_INFO_REQUESTED = 'ON_GET_PLACE_INFO_REQUESTED';
export const ON_GET_PLACE_INFO_SUCCEEDED = 'ON_GET_PLACE_INFO_SUCCEEDED';
export const ON_GET_PLACE_INFO_FAILED = 'ON_GET_PLACE_INFO_FAILED';

export const ON_MAKE_PLACE_RESERVATION_REQUESTED = 'ON_MAKE_PLACE_RESERVATION_REQUESTED';
export const ON_MAKE_PLACE_RESERVATION_SUCCEEDED = 'ON_MAKE_PLACE_RESERVATION_SUCCEEDED';
export const ON_MAKE_PLACE_RESERVATION_FAILED = 'ON_MAKE_PLACE_RESERVATION_FAILED';