export const PROVIDER_ON_SIGN_UP_REQUESTED = 'PROVIDER_ON_SIGN_UP_REQUESTED';
export const PROVIDER_ON_SIGN_UP_SUCCEEDED = 'PROVIDER_ON_SIGN_UP_SUCCEEDED';
export const PROVIDER_ON_SIGN_UP_FAILED = 'PROVIDER_ON_SIGN_UP_FAILED';

export const PROVIDER_ON_LOGIN_REQUESTED = 'PROVIDER_ON_LOGIN_REQUESTED';
export const PROVIDER_ON_LOGIN_SUCCEEDED = 'PROVIDER_ON_LOGIN_SUCCEEDED';
export const PROVIDER_ON_LOGIN_FAILED = 'PROVIDER_ON_LOGIN_FAILED';

export const ON_GET_ALL_CATEGORIES_REQUESTED = 'ON_GET_ALL_CATEGORIES_REQUESTED';
export const ON_GET_ALL_CATEGORIES_SUCCEEDED = 'ON_GET_ALL_CATEGORIES_SUCCEEDED';
export const ON_GET_ALL_CATEGORIES_FAILED = 'ON_GET_ALL_CATEGORIES_FAILED';

export const ON_FILTER_CATEGORY_REQUESTED = 'ON_FILTER_CATEGORY_REQUESTED';
export const ON_FILTER_CATEGORY_SUCCEEDED = 'ON_FILTER_CATEGORY_SUCCEEDED';
export const ON_FILTER_CATEGORY_FAILED = 'ON_FILTER_CATEGORY_FAILED';

export const ON_GET_ALL_PROVIDERS_REQUESTED = 'ON_GET_ALL_PROVIDERS_REQUESTED';
export const ON_GET_ALL_PROVIDERS_SUCCEEDED = 'ON_GET_ALL_PROVIDERS_SUCCEEDED';
export const ON_GET_ALL_PROVIDERS_FAILED = 'ON_GET_ALL_PROVIDERS_FAILED';

export const ON_GET_ALL_PROVIDERS_REVIEWS_REQUESTED = 'ON_GET_ALL_PROVIDERS_REVIEWS_REQUESTED';
export const ON_GET_ALL_PROVIDERS_REVIEWS_SUCCEEDED = 'ON_GET_ALL_PROVIDERS_REVIEWS_SUCCEEDED';
export const ON_GET_ALL_PROVIDERS_REVIEWS_FAILED = 'ON_GET_ALL_PROVIDERS_REVIEWS_FAILED';

export const ON_GET_PROVIDER_INFO_REQUESTED = 'ON_GET_PROVIDER_INFO_REQUESTED';
export const ON_GET_PROVIDER_INFO_SUCCEEDED = 'ON_GET_PROVIDER_INFO_SUCCEEDED';
export const ON_GET_PROVIDER_INFO_FAILED = 'ON_GET_PROVIDER_INFO_FAILED';

export const ON_GET_PROVIDER_SERVICES_REQUESTED = 'ON_GET_PROVIDER_SERVICES_REQUESTED';
export const ON_GET_PROVIDER_SERVICES_SUCCEEDED = 'ON_GET_PROVIDER_SERVICES_SUCCEEDED';
export const ON_GET_PROVIDER_SERVICES_FAILED = 'ON_GET_PROVIDER_SERVICES_FAILED';

export const PROVIDER_ON_SEARCH_NAME_REQUESTED = 'PROVIDER_ON_SEARCH_NAME_REQUESTED';
export const PROVIDER_ON_SEARCH_NAME_SUCCEEDED = 'PROVIDER_ON_SEARCH_NAME_SUCCEEDED';
export const PROVIDER_ON_SEARCH_NAME_FAILED = 'PROVIDER_ON_SEARCH_NAME_FAILED';

export const PROVIDER_ON_GET_PROFILE_INFO_REQUESTED = 'PROVIDER_ON_GET_PROFILE_INFO_REQUESTED';
export const PROVIDER_ON_GET_PROFILE_INFO_SUCCEEDED = 'PROVIDER_ON_GET_PROFILE_INFO_SUCCEEDED';
export const PROVIDER_ON_GET_PROFILE_INFO_FAILED = 'PROVIDER_ON_GET_PROFILE_INFO_FAILED';

export const PROVIDER_ON_CREATE_SERVICE_REQUESTED = 'PROVIDER_ON_CREATE_SERVICE_REQUESTED';
export const PROVIDER_ON_CREATE_SERVICE_SUCCEEDED = 'PROVIDER_ON_CREATE_SERVICE_SUCCEEDED';
export const PROVIDER_ON_CREATE_SERVICE_FAILED = 'PROVIDER_ON_CREATE_SERVICE_FAILED';

export const PROVIDER_ON_EDIT_SERVICE_REQUESTED = 'PROVIDER_ON_EDIT_SERVICE_REQUESTED';
export const PROVIDER_ON_EDIT_SERVICE_SUCCEEDED = 'PROVIDER_ON_EDIT_SERVICE_SUCCEEDED';
export const PROVIDER_ON_EDIT_SERVICE_FAILED = 'PROVIDER_ON_EDIT_SERVICE_FAILED';

export const PROVIDER_ON_UPDATE_PROFILE_REQUESTED = 'PROVIDER_ON_UPDATE_PROFILE_REQUESTED';
export const PROVIDER_ON_UPDATE_PROFILE_SUCCEEDED = 'PROVIDER_ON_UPDATE_PROFILE_SUCCEEDED';
export const PROVIDER_ON_UPDATE_PROFILE_FAILED = 'PROVIDER_ON_UPDATE_PROFILE_FAILED';
