export const PROVIDER_ON_SIGN_UP_REQUESTED = 'PROVIDER_ON_SIGN_UP_REQUESTED';
export const PROVIDER_ON_SIGN_UP_SUCCEEDED = 'PROVIDER_ON_SIGN_UP_SUCCEEDED';
export const PROVIDER_ON_SIGN_UP_FAILED = 'PROVIDER_ON_SIGN_UP_FAILED';

export const PROVIDER_ON_LOGIN_REQUESTED = 'PROVIDER_ON_LOGIN_REQUESTED';
export const PROVIDER_ON_LOGIN_SUCCEEDED = 'PROVIDER_ON_LOGIN_SUCCEEDED';
export const PROVIDER_ON_LOGIN_FAILED = 'PROVIDER_ON_LOGIN_FAILED';

export const ON_GET_ALL_CATEGORIES_REQUESTED = 'ON_GET_ALL_CATEGORIES_REQUESTED';
export const ON_GET_ALL_CATEGORIES_SUCCEEDED = 'ON_GET_ALL_CATEGORIES_SUCCEEDED';
export const ON_GET_ALL_CATEGORIES_FAILED = 'ON_GET_ALL_CATEGORIES_FAILED';

export const ON_FILTER_CATEGORY_REQUESTED = 'ON_FILTER_CATEGORY_REQUESTED';
export const ON_FILTER_CATEGORY_SUCCEEDED = 'ON_FILTER_CATEGORY_SUCCEEDED';
export const ON_FILTER_CATEGORY_FAILED = 'ON_FILTER_CATEGORY_FAILED';
