export const USER_ON_INITIALIZE_REQUESTED = 'USER_ON_INITIALIZE_REQUESTED';
export const USER_ON_INITIALIZE_SUCCEEDED = 'USER_ON_INITIALIZE_SUCCEEDED';
export const USER_ON_INITIALIZE_FAILED = 'USER_ON_INITIALIZE_FAILED';

export const USER_ON_LOGIN_REQUESTED = 'USER_ON_LOGIN_REQUESTED';
export const USER_ON_LOGIN_SUCCEEDED = 'USER_ON_LOGIN_SUCCEEDED';
export const USER_ON_LOGIN_FAILED = 'USER_ON_LOGIN_FAILED';

export const USER_ON_SIGN_UP_REQUESTED = 'USER_ON_SIGN_UP_REQUESTED';
export const USER_ON_SIGN_UP_SUCCEEDED = 'USER_ON_SIGN_UP_SUCCEEDED';
export const USER_ON_SIGN_UP_FAILED = 'USER_ON_SIGN_UP_FAILED';


export const USER_ON_LOGOUT_REQUESTED = 'USER_ON_LOGOUT_REQUESTED';
export const USER_ON_LOGOUT_SUCCEEDED = 'USER_ON_LOGOUT_SUCCEEDED';
export const USER_ON_LOGOUT_FAILED = 'USER_ON_LOGOUT_FAILED';

export const USER_ON_REGISTER_A_CLAIM_REQUESTED = 'USER_ON_REGISTER_A_CLAIM_REQUESTED';
export const USER_ON_REGISTER_A_CLAIM_SUCCEEDED = 'USER_ON_REGISTER_A_CLAIM_SUCCEEDED';
export const USER_ON_REGISTER_A_CLAIM_FAILED = 'USER_ON_REGISTER_A_CLAIM_FAILED';

export const USER_ON_GET_CLAIMS_REQUESTED = 'USER_ON_GET_CLAIMS_REQUESTED';
export const USER_ON_GET_CLAIMS_SUCCEEDED = 'USER_ON_GET_CLAIMS_SUCCEEDED';
export const USER_ON_GET_CLAIMS_FAILED = 'USER_ON_GET_CLAIMS_FAILED';

export const USER_ON_EDIT_CLAIM_REQUESTED = 'USER_ON_EDIT_CLAIM_REQUESTED';
export const USER_ON_EDIT_CLAIM_SUCCEEDED = 'USER_ON_EDIT_CLAIM_SUCCEEDED';
export const USER_ON_EDIT_CLAIM_FAILED = 'USER_ON_EDIT_CLAIM_FAILED';

export const USER_ON_MAKE_RESERVATION_REQUESTED = 'USER_ON_MAKE_RESERVATION_REQUESTED';
export const USER_ON_MAKE_RESERVATION_SUCCEEDED = 'USER_ON_MAKE_RESERVATION_SUCCEEDED';
export const USER_ON_MAKE_RESERVATION_FAILED = 'USER_ON_MAKE_RESERVATION_FAILED';

export const USER_ON_POST_COMMENT_REQUESTED = 'USER_ON_POST_COMMENT_REQUESTED';
export const USER_ON_POST_COMMENT_SUCCEEDED = 'USER_ON_POST_COMMENT_SUCCEEDED';
export const USER_ON_POST_COMMENT_FAILED = 'USER_ON_POST_COMMENT_FAILED';
