export const USER_ON_INITIALIZE_REQUESTED = 'USER_ON_INITIALIZE_REQUESTED';
export const USER_ON_INITIALIZE_SUCCEEDED = 'USER_ON_INITIALIZE_SUCCEEDED';
export const USER_ON_INITIALIZE_FAILED = 'USER_ON_INITIALIZE_FAILED';

export const USER_ON_GET_PROFILE_INFO_REQUESTED = 'USER_ON_GET_PROFILE_INFO_REQUESTED';
export const USER_ON_GET_PROFILE_INFO_SUCCEEDED = 'USER_ON_GET_PROFILE_INFO_SUCCEEDED';
export const USER_ON_GET_PROFILE_INFO_FAILED = 'USER_ON_GET_PROFILE_INFO_FAILED';

export const USER_ON_LOGIN_REQUESTED = 'USER_ON_LOGIN_REQUESTED';
export const USER_ON_LOGIN_SUCCEEDED = 'USER_ON_LOGIN_SUCCEEDED';
export const USER_ON_LOGIN_FAILED = 'USER_ON_LOGIN_FAILED';

export const USER_ON_SIGN_UP_REQUESTED = 'USER_ON_SIGN_UP_REQUESTED';
export const USER_ON_SIGN_UP_SUCCEEDED = 'USER_ON_SIGN_UP_SUCCEEDED';
export const USER_ON_SIGN_UP_FAILED = 'USER_ON_SIGN_UP_FAILED';

export const USER_ON_LOGOUT = 'USER_ON_LOGOUT';

export const USER_ON_REGISTER_A_CLAIM_REQUESTED = 'USER_ON_REGISTER_A_CLAIM_REQUESTED';
export const USER_ON_REGISTER_A_CLAIM_SUCCEEDED = 'USER_ON_REGISTER_A_CLAIM_SUCCEEDED';
export const USER_ON_REGISTER_A_CLAIM_FAILED = 'USER_ON_REGISTER_A_CLAIM_FAILED';

export const USER_ON_GET_CLAIMS_REQUESTED = 'USER_ON_GET_CLAIMS_REQUESTED';
export const USER_ON_GET_CLAIMS_SUCCEEDED = 'USER_ON_GET_CLAIMS_SUCCEEDED';
export const USER_ON_GET_CLAIMS_FAILED = 'USER_ON_GET_CLAIMS_FAILED';

export const USER_ON_EDIT_CLAIM_REQUESTED = 'USER_ON_EDIT_CLAIM_REQUESTED';
export const USER_ON_EDIT_CLAIM_SUCCEEDED = 'USER_ON_EDIT_CLAIM_SUCCEEDED';
export const USER_ON_EDIT_CLAIM_FAILED = 'USER_ON_EDIT_CLAIM_FAILED';

export const USER_ON_MAKE_RESERVATION_REQUESTED = 'USER_ON_MAKE_RESERVATION_REQUESTED';
export const USER_ON_MAKE_RESERVATION_SUCCEEDED = 'USER_ON_MAKE_RESERVATION_SUCCEEDED';
export const USER_ON_MAKE_RESERVATION_FAILED = 'USER_ON_MAKE_RESERVATION_FAILED';

export const USER_ON_POST_COMMENT_REQUESTED = 'USER_ON_POST_COMMENT_REQUESTED';
export const USER_ON_POST_COMMENT_SUCCEEDED = 'USER_ON_POST_COMMENT_SUCCEEDED';
export const USER_ON_POST_COMMENT_FAILED = 'USER_ON_POST_COMMENT_FAILED';

export const USER_ON_GET_ALL_RESERVATIONS_REQUESTED = 'USER_ON_GET_ALL_RESERVATIONS_REQUESTED';
export const USER_ON_GET_ALL_RESERVATIONS_SUCCEEDED = 'USER_ON_GET_ALL_RESERVATIONS_SUCCEEDED';
export const USER_ON_GET_ALL_RESERVATIONS_FAILED = 'USER_ON_GET_ALL_RESERVATIONS_FAILED';

export const USER_ON_CANCEL_RESERVATION_REQUESTED = 'USER_ON_CANCEL_RESERVATION_REQUESTED';
export const USER_ON_CANCEL_RESERVATION_SUCCEEDED = 'USER_ON_CANCEL_RESERVATION_SUCCEEDED';
export const USER_ON_CANCEL_RESERVATION_FAILED = 'USER_ON_CANCEL_RESERVATION_FAILED';

export const USER_ON_GET_REVIEWS_REQUESTED = 'USER_ON_GET_REVIEWS_REQUESTED';
export const USER_ON_GET_REVIEWS_SUCCEEDED = 'USER_ON_GET_REVIEWS_SUCCEEDED';
export const USER_ON_GET_REVIEWS_FAILED = 'USER_ON_GET_REVIEWS_FAILED';

export const USER_ON_LEAVE_A_REVIEW_REQUESTED = 'USER_ON_LEAVE_A_REVIEW_REQUESTED';
export const USER_ON_LEAVE_A_REVIEW_SUCCEEDED = 'USER_ON_LEAVE_A_REVIEW_SUCCEEDED';
export const USER_ON_LEAVE_A_REVIEW_FAILED = 'USER_ON_LEAVE_A_REVIEW_FAILED';

export const USER_ON_PAY_RESERVATION_REQUESTED = 'USER_ON_PAY_RESERVATION_REQUESTED';
export const USER_ON_PAY_RESERVATION_SUCCEEDED = 'USER_ON_PAY_RESERVATION_SUCCEEDED';
export const USER_ON_PAY_RESERVATION_FAILED = 'USER_ON_PAY_RESERVATION_FAILED';

export const USER_ON_GET_PHOTO_REQUESTED = 'USER_ON_GET_PHOTO_REQUESTED';
export const USER_ON_GET_PHOTO_SUCCEEDED = 'USER_ON_GET_PHOTO_SUCCEEDED';
export const USER_ON_GET_PHOTO_FAILED = 'USER_ON_GET_PHOTO_FAILED';

export const USER_ON_UPDATE_PROFILE_REQUESTED = 'USER_ON_UPDATE_PROFILE_REQUESTED';
export const USER_ON_UPDATE_PROFILE_SUCCEEDED = 'USER_ON_UPDATE_PROFILE_SUCCEEDED';
export const USER_ON_UPDATE_PROFILE_FAILED = 'USER_ON_UPDATE_PROFILE_FAILED';

export const USER_ON_UPDATE_PASSWORD_REQUESTED = 'USER_ON_UPDATE_PASSWORD_REQUESTED';
export const USER_ON_UPDATE_PASSWORD_SUCCEEDED = 'USER_ON_UPDATE_PASSWORD_SUCCEEDED';
export const USER_ON_UPDATE_PASSWORD_FAILED = 'USER_ON_UPDATE_PASSWORD_FAILED';

export const USER_ON_GET_CARDS_REQUESTED = 'USER_ON_GET_CARDS_REQUESTED';
export const USER_ON_GET_CARDS_SUCCEEDED = 'USER_ON_GET_CARDS_SUCCEEDED';
export const USER_ON_GET_CARDS_FAILED = 'USER_ON_GET_CARDS_FAILED';

export const USER_ON_ADD_NEW_CARD_REQUESTED = 'USER_ON_ADD_NEW_CARD_REQUESTED';
export const USER_ON_ADD_NEW_CARD_SUCCEEDED = 'USER_ON_ADD_NEW_CARD_SUCCEEDED';
export const USER_ON_ADD_NEW_CARD_FAILED = 'USER_ON_ADD_NEW_CARD_FAILED';

export const USER_ON_DELETE_CARD_REQUESTED = 'USER_ON_DELETE_CARD_REQUESTED';
export const USER_ON_DELETE_CARD_SUCCEEDED = 'USER_ON_DELETE_CARD_SUCCEEDED';
export const USER_ON_DELETE_CARD_FAILED = 'USER_ON_DELETE_CARD_FAILED';

export const USER_ON_GET_PLACES_RESERVATIONS_REQUESTED = 'USER_ON_GET_PLACES_RESERVATIONS_REQUESTED';
export const USER_ON_GET_PLACES_RESERVATIONS_SUCCEEDED = 'USER_ON_GET_PLACES_RESERVATIONS_SUCCEEDED';
export const USER_ON_GET_PLACES_RESERVATIONS_FAILED = 'USER_ON_GET_PLACES_RESERVATIONS_FAILED';
